In [1]:
import numpy as np

a = np.float32(24.58172)
b = 46
c = "23"

print(a < b)
print(b == 2*c)

True
False


In [7]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
c = np.array([1,2,3])
d = np.array([
    [1,2,3,4],
    [5,4,7,8]])
e = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8],
    [9,8,7]])
f = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1],
    [0,1,2]])

print(a@b)
print(a*b)
print(f@c)
# print(f@a)
print(d@d.T)

20
[4 6 6 4]
[46 28 10  8]
[[ 30  66]
 [ 66 154]]
